<?php

declare(strict_types=1);

namespace Webhook\Application\Port\Outbound;

use Webhook\Domain\Model\Delivery\WebhookDelivery;
use Webhook\Domain\ValueObject\{WebhookDeliveryId, WebhookSubscriptionId};

/**
 * Port WebhookDeliveryRepositoryPort.
 *
 * @category Port
 *
 * @version 1.0.0
 *
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
interface WebhookDeliveryRepositoryPort
{
  // #region Methods
  /**
   * Method reserve.
   *
   * Idempotently reserves one pending delivery row for a
   * `(subscriptionId, eventId)` pair via a raw-DBAL unique-insert, mirroring
   * `Automation\Infrastructure\Persistence\Doctrine\Repository\AutomationRunRepository::reserveRun()`:
   * a unique-constraint violation during an ORM `flush()` closes the
   * EntityManager, so a duplicate reservation attempt (fan-out re-run, or
   * the same source event delivered twice) is handled as a routine,
   * expected outcome here rather than an exceptional one.
   *
   * The delivery identifier is generated by the CALLER (not here) so it can
   * be embedded as `WebhookPayloadEnvelope::$id` — the consumer-facing
   * idempotency key — before the envelope is persisted as `payload`.
   *
   * @since 1.0.0
   *
   * @param WebhookDeliveryId $id the pre-generated delivery identifier
   * @param WebhookSubscriptionId $subscriptionId the target subscription identifier
   * @param string $organizationId the owning organization identifier
   * @param string $eventType the public event type delivered
   * @param string $eventId the source domain event identifier (dedupe key)
   * @param array<string, mixed> $payload the rendered public payload envelope
   *
   * @return bool true when this call reserved the row, false when a delivery
   *              for this `(subscriptionId, eventId)` pair already exists
   */
  public function reserve(
    WebhookDeliveryId $id,
    WebhookSubscriptionId $subscriptionId,
    string $organizationId,
    string $eventType,
    string $eventId,
    array $payload,
  ): bool;

  /**
   * Method save.
   *
   * Persists a delivery's mutable lifecycle fields (status, attempts,
   * httpStatus, lastError, nextRetryAt, deliveredAt).
   *
   * @since 1.0.0
   *
   * @param WebhookDelivery $delivery the webhook delivery aggregate
   */
  public function save(WebhookDelivery $delivery): void;

  /**
   * Method findById.
   *
   * @since 1.0.0
   *
   * @param WebhookDeliveryId $id the webhook delivery identifier
   *
   * @return ?WebhookDelivery the delivery, or null when not found
   */
  public function findById(WebhookDeliveryId $id): ?WebhookDelivery;

  /**
   * Method listBySubscription.
   *
   * @since 1.0.0
   *
   * @param WebhookSubscriptionId $subscriptionId the target subscription identifier
   * @param ?string $status optional status filter
   * @param int $limit maximum number of results
   * @param int $offset result offset
   *
   * @return list<WebhookDelivery> the matching deliveries, most recent first
   */
  public function listBySubscription(WebhookSubscriptionId $subscriptionId, ?string $status, int $limit, int $offset): array;

  /**
   * Method countBySubscription.
   *
   * @since 1.0.0
   *
   * @param WebhookSubscriptionId $subscriptionId the target subscription identifier
   * @param ?string $status optional status filter
   *
   * @return int the matching delivery count
   */
  public function countBySubscription(WebhookSubscriptionId $subscriptionId, ?string $status): int;
  // #endregion
}
