api_platform:
  title: Fireguard Auth API
  description: OAuth2 and OpenID Connect Authorization Server
  version: 1.0.0
  defaults:
    stateless: true
    cache_headers:
      vary: ["Content-Type", "Authorization", "Origin"]
  mapping:
    paths:
      - '%kernel.project_dir%/src/Auth/Presentation/Resource'
      - '%kernel.project_dir%/src/Client/Presentation/Api/Resource'
      - '%kernel.project_dir%/src/User/Presentation/Api/Resource'
