framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    queue_name: async
            # failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        routing:
            'Mission\Application\UseCase\Command\Publication\ExecutePublication\ExecutePublicationCommand': async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'
