nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ["%env(default:default_cors_allow_origin:CORS_ALLOW_ORIGIN)%"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
    allow_headers: ["Content-Type", "Authorization", "X-Requested-With", "Accept", "Origin"]
    expose_headers: ["Link"]
    max_age: 3600
    allow_credentials: true
  paths:
    "^/": null

parameters:
  default_cors_allow_origin: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
