framework:
  rate_limiter:
    login:
      policy: 'sliding_window'
      limit: 5
      interval: '1 minute'
    oauth_token:
      policy: 'sliding_window'
      limit: 20
      interval: '1 minute'
    oauth_introspection:
      policy: 'sliding_window'
      limit: 60
      interval: '1 minute'
    oauth_revocation:
      policy: 'sliding_window'
      limit: 30
      interval: '1 minute'
