<?php

declare(strict_types=1);

namespace Organization\Presentation\Api\Resource;

use ApiPlatform\Metadata\{ApiResource, Delete, Get, Patch, Post};
use ApiPlatform\OpenApi\Model\Operation;
use Organization\Presentation\Api\Dto\Input\Join\{ApproveOrganizationJoinRequestInput, OrganizationAccessPolicyInput, OrganizationDomainInput};
use Organization\Presentation\Api\Dto\Output\Join\{OrganizationAccessPolicyOutput, OrganizationDomainOutput, OrganizationJoinCompletedOutput, OrganizationJoinOptionsOutput, OrganizationJoinRequestOutput, OrganizationJoinRequestsOutput};
use Organization\Presentation\Api\Operation\OrganizationJoinOperations;
use Organization\Presentation\Api\Processor\Join\OrganizationJoinProcessor;
use Organization\Presentation\Api\Provider\Join\OrganizationJoinProvider;
use Organization\Presentation\Api\Serialization\OrganizationSerializationGroup;

/**
 * Resource OrganizationJoinResource.
 *
 * @category Resource
 *
 * @version 1.0.0
 *
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
#[ApiResource(shortName: 'OrganizationJoin', routePrefix: '/organizations', operations: [
  new Get(name: OrganizationJoinOperations::JOIN_OPTIONS, uriTemplate: '/join-options', read: true, input: false, output: OrganizationJoinOptionsOutput::class, provider: OrganizationJoinProvider::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'options'], openapi: new Operation(tags: ['Organization access'], summary: 'join options')),
  new Get(name: OrganizationJoinOperations::MY_REQUESTS, uriTemplate: '/join-requests', read: true, input: false, output: OrganizationJoinRequestsOutput::class, provider: OrganizationJoinProvider::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'requests'], openapi: new Operation(tags: ['Organization access'], summary: 'my requests')),
  new Get(name: OrganizationJoinOperations::ACCESS_POLICY, uriTemplate: '/{organizationId}/access-policy', read: true, input: false, output: OrganizationAccessPolicyOutput::class, provider: OrganizationJoinProvider::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'policy'], openapi: new Operation(tags: ['Organization access'], summary: 'access policy')),
  new Patch(name: OrganizationJoinOperations::UPDATE_ACCESS_POLICY, uriTemplate: '/{organizationId}/access-policy', read: false, status: 200, input: OrganizationAccessPolicyInput::class, output: OrganizationAccessPolicyOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'policy'], openapi: new Operation(tags: ['Organization access'], summary: 'update access policy')),
  new Post(name: OrganizationJoinOperations::ADD_DOMAIN, uriTemplate: '/{organizationId}/domains', read: false, status: 200, input: OrganizationDomainInput::class, output: OrganizationDomainOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'domain_add'], openapi: new Operation(tags: ['Organization access'], summary: 'add domain')),
  new Post(name: OrganizationJoinOperations::VERIFY_DOMAIN, uriTemplate: '/{organizationId}/domains/{domainId}/verify', read: false, status: 200, input: false, output: OrganizationDomainOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'domain_verify'], openapi: new Operation(tags: ['Organization access'], summary: 'verify domain')),
  new Delete(name: OrganizationJoinOperations::REMOVE_DOMAIN, uriTemplate: '/{organizationId}/domains/{domainId}', read: false, status: 200, input: false, output: OrganizationJoinCompletedOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'domain_remove'], openapi: new Operation(tags: ['Organization access'], summary: 'remove domain')),
  new Post(name: OrganizationJoinOperations::JOIN, uriTemplate: '/{organizationId}/join', read: false, status: 200, input: false, output: OrganizationJoinCompletedOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'join'], openapi: new Operation(tags: ['Organization access'], summary: 'join')),
  new Post(name: OrganizationJoinOperations::REQUEST, uriTemplate: '/{organizationId}/join-requests', read: false, status: 200, input: false, output: OrganizationJoinRequestOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'request'], openapi: new Operation(tags: ['Organization access'], summary: 'request')),
  new Get(name: OrganizationJoinOperations::ORGANIZATION_REQUESTS, uriTemplate: '/{organizationId}/join-requests', read: true, input: false, output: OrganizationJoinRequestsOutput::class, provider: OrganizationJoinProvider::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'organization_requests'], openapi: new Operation(tags: ['Organization access'], summary: 'organization requests')),
  new Post(name: OrganizationJoinOperations::APPROVE_REQUEST, uriTemplate: '/{organizationId}/join-requests/{requestId}/approve', read: false, status: 200, input: ApproveOrganizationJoinRequestInput::class, output: OrganizationJoinRequestOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'approve'], openapi: new Operation(tags: ['Organization access'], summary: 'approve request')),
  new Post(name: OrganizationJoinOperations::REJECT_REQUEST, uriTemplate: '/{organizationId}/join-requests/{requestId}/reject', read: false, status: 200, input: false, output: OrganizationJoinRequestOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'reject'], openapi: new Operation(tags: ['Organization access'], summary: 'reject request')),
  new Post(name: OrganizationJoinOperations::CANCEL_REQUEST, uriTemplate: '/join-requests/{requestId}/cancel', read: false, status: 200, input: false, output: OrganizationJoinRequestOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'cancel'], openapi: new Operation(tags: ['Organization access'], summary: 'cancel request')),
  new Post(name: OrganizationJoinOperations::ACCEPT_INVITATION_BY_ID, uriTemplate: '/invitations/{invitationId}/accept', read: false, status: 200, input: false, output: OrganizationJoinCompletedOutput::class, processor: OrganizationJoinProcessor::class, security: "is_granted('ROLE_USER')", normalizationContext: ['groups' => [OrganizationSerializationGroup::READ]], denormalizationContext: ['groups' => [OrganizationSerializationGroup::WRITE]], extraProperties: ['join_action' => 'accept_invitation'], openapi: new Operation(tags: ['Organization access'], summary: 'accept invitation by id')),
])]
final class OrganizationJoinResource
{
}
