<?php

declare(strict_types=1);

namespace Tests\Unit\Shared\Infrastructure\Symfony\Adapter\Outbound;

use Exception;
use PHPUnit\Framework\Attributes\{CoversClass, Test};
use PHPUnit\Framework\TestCase;
use Shared\Infrastructure\Exception\UuidGenerationException;
use Shared\Infrastructure\Symfony\Adapter\Outbound\UuidGeneratorAdapter;
use Symfony\Component\Uid\Uuid;

/**
 * Class UuidGeneratorAdapterTest.
 *
 * Unit tests for the UuidGeneratorAdapter.
 *
 * @category Unit Test
 *
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 *
 * @covers \Shared\Infrastructure\Symfony\Adapter\Outbound\UuidGeneratorAdapter
 */
#[CoversClass(className: UuidGeneratorAdapter::class)]
final class UuidGeneratorAdapterTest extends TestCase
{
  /**
   * Test that a valid UUID is generated by default.
   */
  #[Test]
  public function testGenerateDefault(): void
  {
    $adapter = new UuidGeneratorAdapter();
    $uuid = $adapter->generate();

    $this->assertTrue(Uuid::isValid($uuid));
  }

  /**
   * Test that a custom generator can be used.
   */
  #[Test]
  public function testGenerateWithCustomGenerator(): void
  {
    $customUuid = Uuid::v4();
    $generator = fn () => $customUuid;
    $adapter = new UuidGeneratorAdapter($generator);

    $this->assertEquals($customUuid->toRfc4122(), $adapter->generate());
  }

  /**
   * Test that generation fails and throws a UuidGenerationException.
   */
  #[Test]
  public function testGenerateThrowsException(): void
  {
    $generator = fn () => throw new Exception('Generation failed');
    $adapter = new UuidGeneratorAdapter($generator);

    $this->expectException(UuidGenerationException::class);
    $adapter->generate();
  }
}
