services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Handlers
    Client\Application\UseCase\:
        resource: '../../src/Client/Application/UseCase/'

    # Repository
    Client\Infrastructure\Persistence\Doctrine\Repository\ClientRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    # Port Binding
    Client\Application\Port\Outbound\ClientRepositoryPort:
        alias: Client\Infrastructure\Persistence\Doctrine\Repository\ClientRepository
