services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Handlers
    Client\Application\UseCase\:
        resource: '../../src/Client/Application/UseCase/'

    Client\Application\UseCase\Query\ValidateClientCredentials\ValidateClientCredentialsHandler:
        tags:
            - { name: messenger.message_handler, handles: Client\Application\UseCase\Query\ValidateClientCredentials\ValidateClientCredentialsQuery }

    Client\Application\UseCase\Query\GetClient\GetClientHandler:
        tags:
            - { name: messenger.message_handler, handles: Client\Application\UseCase\Query\GetClient\GetClientQuery }

    # Repository
    Client\Infrastructure\Persistence\Doctrine\Repository\ClientRepository:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    Client\Infrastructure\Persistence\Doctrine\Mapper\ClientMapper: ~

    # Port Binding
    Client\Application\Port\Outbound\ClientRepositoryPort:
        alias: Client\Infrastructure\Persistence\Doctrine\Repository\ClientRepository

    # Console Commands
    Client\Infrastructure\Symfony\Command\CreateClientCommand:
        tags: ['console.command']

    Client\Infrastructure\Symfony\Command\ListClientsCommand:
        tags: ['console.command']

    Client\Infrastructure\Symfony\Command\DeleteClientCommand:
        tags: ['console.command']

    # DataFixtures
    Client\Infrastructure\DataFixtures\ClientFixtures:
        tags: ['doctrine.fixture.orm']
