services:
  _defaults:
    autowire: true
    autoconfigure: true

  # OAuth Module - Validators
  OAuth\Presentation\Api\Validator\ValidScopes\ValidScopes\ValidScopesValidator: ~
  OAuth\Presentation\Api\Validator\ValidRedirectUri\ValidRedirectUri\ValidRedirectUriValidator: ~

  # UseCases - Auto-register
  OAuth\Application\UseCase\:
    resource: '../../src/OAuth/Application/UseCase/'

  OAuth\Application\Service\OidcClaimsBuilder: ~

  OAuth\Application\Service\OidcClaimsBuilderInterface:
    alias: OAuth\Application\Service\OidcClaimsBuilder

  # Client Query Handlers
  OAuth\Application\UseCase\Query\Client\ValidateClientCredentials\ValidateClientCredentialsHandler:
    tags:
      - { name: messenger.message_handler, handles: OAuth\Application\UseCase\Query\Client\ValidateClientCredentials\ValidateClientCredentialsQuery }

  OAuth\Application\UseCase\Query\Client\GetClient\GetClientHandler:
    tags:
      - { name: messenger.message_handler, handles: OAuth\Application\UseCase\Query\Client\GetClient\GetClientQuery }

  # Repository
  OAuth\Infrastructure\Persistence\Doctrine\Repository\Client\ClientRepository:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'

  OAuth\Infrastructure\Persistence\Doctrine\Mapper\Client\ClientMapper: ~

  # Port Binding
  OAuth\Application\Port\Outbound\Token\JwtParserPort:
    alias: Auth\Infrastructure\Adapter\Jwt\JwtParserAdapter

  OAuth\Application\Port\Outbound\Client\ClientRepositoryPort:
    alias: OAuth\Infrastructure\Persistence\Doctrine\Repository\Client\ClientRepository



  OAuth\Application\Port\Outbound\Client\OAuthClientRepositoryPort:
    alias: OAuth\Infrastructure\Persistence\Doctrine\Repository\Client\ClientRepository

  OAuth\Application\Port\Outbound\Token\IdTokenIssuerPort:
    alias: OAuth\Infrastructure\Oidc\Adapter\IdTokenIssuerAdapter

  # Console Commands
  OAuth\Infrastructure\Console\Command\Client\CreateClientCommand: ~
  OAuth\Infrastructure\Console\Command\Client\ListClientsCommand: ~
  OAuth\Infrastructure\Console\Command\Client\DeleteClientCommand: ~

  # DataFixtures
  OAuth\Infrastructure\DataFixtures\ClientFixtures:
    tags: ['doctrine.fixture.orm']

  # Event Subscribers
  OAuth\Infrastructure\EventSubscriber\EventLogSubscriber: ~
  OAuth\Presentation\Api\EventSubscriber\OAuthErrorSubscriber: ~
  OAuth\Presentation\Api\EventSubscriber\OAuthResponseSubscriber: ~

  # OIDC Adapter
  OAuth\Infrastructure\Oidc\Adapter\IdTokenIssuerAdapter: ~

  # OAuth Processors
  OAuth\Presentation\Api\Processor\Authorization\AuthorizeProcessor: ~
  OAuth\Presentation\Api\Processor\Consent\GrantConsentProcessor: ~
