services:
  _defaults:
    autowire: true
    autoconfigure: true

  Onboarding\Presentation\:
    resource: '../../src/Onboarding/Presentation'

  onboarding.main_transaction_manager:
    class: Shared\Infrastructure\Symfony\Adapter\Outbound\DoctrineTransactionManagerAdapter
    arguments:
      $entityManager: '@doctrine.orm.main_entity_manager'

  Onboarding\Infrastructure\Persistence\Doctrine\Repository\OrganizationOnboardingSessionRepository:
    arguments:
      $entityManager: '@doctrine.orm.main_entity_manager'

  Onboarding\Application\Port\Outbound\OrganizationOnboardingSessionRepositoryPort:
    alias: Onboarding\Infrastructure\Persistence\Doctrine\Repository\OrganizationOnboardingSessionRepository

  Onboarding\Application\Service\OrganizationOnboardingFlowService:
    arguments:
      $transactionManager: '@onboarding.main_transaction_manager'

  Onboarding\Application\Port\Inbound\OrganizationOnboardingServicePort:
    alias: Onboarding\Application\Service\OrganizationOnboardingFlowService

  Onboarding\Infrastructure\EventSubscriber\OnboardingNotificationSubscriber: ~

  Onboarding\Infrastructure\Persistence\Doctrine\Repository\OrganizationSetupRepository:
    arguments:
      $entityManager: '@doctrine.orm.main_entity_manager'

  Onboarding\Application\Port\Outbound\OrganizationSetupRepositoryPort:
    alias: Onboarding\Infrastructure\Persistence\Doctrine\Repository\OrganizationSetupRepository

  Onboarding\Application\Service\OrganizationSetupService:
    arguments:
      $transactionManager: '@onboarding.main_transaction_manager'

  Onboarding\Application\UseCase\Command\Setup\PrepareOrganizationSetup\PrepareOrganizationSetupHandler:
    tags: ['messenger.message_handler']

  Onboarding\Application\Port\Inbound\OrganizationSetupPort:
    alias: Onboarding\Application\Service\OrganizationSetupService
