services:
  _defaults:
    autowire: true
    autoconfigure: false

  User\Infrastructure\DataFixtures\UserFixtures:
    tags:
      - { name: 'app.seed_fixture.auth' }

  Authorization\Infrastructure\DataFixtures\AuthorizationFixtures:
    tags:
      - { name: 'app.seed_fixture.auth' }

  OAuth\Infrastructure\DataFixtures\ClientFixtures:
    tags:
      - { name: 'app.seed_fixture.auth' }

  Organization\Infrastructure\DataFixtures\PlanFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Organization\Infrastructure\DataFixtures\OrganizationFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Onboarding\Infrastructure\DataFixtures\OnboardingFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Facility\Infrastructure\DataFixtures\FacilityFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Equipment\Infrastructure\DataFixtures\EquipmentFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Inspection\Infrastructure\DataFixtures\InspectionFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Maintenance\Infrastructure\DataFixtures\MaintenanceFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Intervention\Infrastructure\DataFixtures\InterventionFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Calendar\Infrastructure\DataFixtures\CalendarFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }

  Messaging\Infrastructure\DataFixtures\MessagingFixtures:
    tags:
      - { name: 'app.seed_fixture.main' }
