<?php

declare(strict_types=1);

namespace Otp\Presentation\Api\Dto\Input\Totp;

use ApiPlatform\Metadata\ApiProperty;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * DTO ConfirmTotpInput.
 *
 * @category DTO
 *
 * @version 1.0.0
 *
 * @author Valentin FORTIN <contact@valentin-fortin.pro>
 */
final class ConfirmTotpInput
{
  // #region Properties
  /**
   * Property code.
   *
   * The TOTP code generated by the authenticator app for the pending secret.
   */
  #[Assert\NotBlank]
  #[ApiProperty(
    description: 'The TOTP code generated by the authenticator app.',
    readable: false,
    writable: true,
    required: true,
    identifier: false,
    example: '123456',
    openapiContext: [
      'type' => 'string',
      'writeOnly' => true,
    ],
  )]
  public string $code;
  // #endregion
}
